### ISSUE TITLE
Allow PHP 8

### ISSUE THREAD

**Issue by StiftungAusNachlass** [vicchi/geojson-rewind#2]
Hi,
please allow the use of PHP8 in composer.json. Seems to work for me if i run composer with "--ignore-platform-reqs"..
Thank you very much

**Comment by timhj** [comment]
No code changes are required, just updating the package definition. There's a pull request in to do it, would be great to do it.

**Comment by vicchi** [comment]
@StiftungAusNachlass Just resolved this as part of PR #3
